### PR TITLE
Fix for Java source file encoding different from UTF-8

### LINKED ISSUE #285: rewriteRun does not respect the source file charset (file.encoding / compileOptions.getEncoding())
## What version of OpenRewrite are you using?

I am using

- OpenRewrite v8.17.1
- Gradle plugin v6.8.4
- rewrite-java v8.17.1

## How are you running OpenRewrite?

I'm using the Gradle Plugin.

## What is the smallest, simplest way to reproduce the problem?

Use a project with source files that are `ISO-8859-1` encoded and contains some Latin-1 characters:
```java
/**
 * Üäé
 */
class A {
}
```

## What did you expect to see?

The file stays intact with `ISO-8859-1` encoding.

## What did you see instead?

```java
/**
 * ���
 */
class A {
}
```

## What is the full stack trace of any errors you encountered?

There's no error

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?

I can offer a draft MR with a quick-fix.

### PR DESCRIPTION
**Pull request by renegrob**
Fixes #285 

## What's changed?

rewriteRun now respects the file encoding of the Gradle Java Plugin

### Checklist
- [ ] I've added unit tests to cover both positive and negative cases
- [ ] I've read and applied the [recipe conventions and best practices](https://docs.openrewrite.org/authoring-recipes/recipe-conventions-and-best-practices)
- [ ] I've used the IntelliJ IDEA auto-formatter on affected files

### CODE REVIEW

**Review by timtebeek — APPROVED** [review]
Thanks a lot for the detailed fix @renegrob ! Review took a little longer with my holiday, but this looks good to me. I take it you already tried it out on projects locally?

**Comment by knutwannheden** [comment]
We might have to do some digging or consult with @shanman190 but I think there is an `encoding` option on the compile task that we should check. The question is just qhen this was added. https://docs.gradle.org/current/dsl/org.gradle.api.tasks.compile.CompileOptions.html#org.gradle.api.tasks.compile.CompileOptions:encoding

**Comment by shanman190** [comment]
@knutwannheden, encoding on CompileOptions has been available since at least Gradle 1.0, I'm not seeing it available in previous versions, but there was a lot of change early on. So for our use case here, it's safe to use at least from the Java compile tasks.

https://docs.gradle.org/1.0/javadoc/org/gradle/api/tasks/compile/CompileOptions.html

**Comment by shanman190** [comment]
@knutwannheden, just to note that @renegrob is already pulling the encoding from the options in this PR as well in case you missed it.

**Comment by renegrob** [comment]
@timtebeek Yes, I'm already using a patched version internally and it is working fine.

**Comment by timtebeek** [comment]
Sounds like we're good to go then; thanks a lot @renegrob for the implementations, and @shanman190 & @knutwannheden for additional review.

**Pull request merged**
